In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Replace the path with the correct path for your data.
y2015 = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1
)

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


# Editing Data

In [96]:
for col in y2015.columns: 
    print(col) 

id
member_id
loan_amnt
funded_amnt
funded_amnt_inv
term
int_rate
installment
grade
sub_grade
emp_title
emp_length
home_ownership
annual_inc
verification_status
issue_d
loan_status
pymnt_plan
url
desc
purpose
title
zip_code
addr_state
dti
delinq_2yrs
earliest_cr_line
inq_last_6mths
mths_since_last_delinq
mths_since_last_record
open_acc
pub_rec
revol_bal
revol_util
total_acc
initial_list_status
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_d
last_pymnt_amnt
next_pymnt_d
last_credit_pull_d
collections_12_mths_ex_med
mths_since_last_major_derog
policy_code
application_type
annual_inc_joint
dti_joint
verification_status_joint
acc_now_delinq
tot_coll_amt
tot_cur_bal
open_acc_6m
open_il_6m
open_il_12m
open_il_24m
mths_since_rcnt_il
total_bal_il
il_util
open_rv_12m
open_rv_24m
max_bal_bc
all_util
total_rev_hi_lim
inq_fi
total_cu_tl
inq_last_12m
acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc

In [97]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)

id
term
int_rate
grade
sub_grade
emp_title
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
url
desc
purpose
title
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
next_pymnt_d
last_credit_pull_d
application_type
verification_status_joint


In [98]:
#Data Cleaning

# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop object columns 
y2015.drop([
'term',
'int_rate',
'grade',
'sub_grade',
'emp_title',
'emp_length',
'home_ownership',
'verification_status',
'issue_d',
#'loan_status',
'pymnt_plan',
'url',
'desc',
'purpose',
'title',
'zip_code',
'addr_state',
'earliest_cr_line',
'revol_util',
'initial_list_status',
'last_pymnt_d',
'next_pymnt_d',
'last_credit_pull_d',
'application_type',
'verification_status_joint'
           ], 1, inplace=True)

# Remove two summary rows at the end that don't actually contain data.
y2015 = y2015[:-2]


In [99]:
for col in y2015.columns: 
    print(col) 

id
member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
loan_status
dti
delinq_2yrs
inq_last_6mths
mths_since_last_delinq
mths_since_last_record
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
mths_since_last_major_derog
policy_code
annual_inc_joint
dti_joint
acc_now_delinq
tot_coll_amt
tot_cur_bal
open_acc_6m
open_il_6m
open_il_12m
open_il_24m
mths_since_rcnt_il
total_bal_il
il_util
open_rv_12m
open_rv_24m
max_bal_bc
all_util
total_rev_hi_lim
inq_fi
total_cu_tl
inq_last_12m
acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc_util
chargeoff_within_12_mths
delinq_amnt
mo_sin_old_il_acct
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl
mort_acc
mths_since_recent_bc
mths_since_recent_bc_dlq
mths_since_recent_inq
mths_since_recent_revol_delinq
num_accts_ever_120_pd
num_actv_bc_tl
num_actv_rev_tl
num

In [100]:
# Drop extra columns, commented columns are kept 
y2015.drop([
#'id',
'member_id',
#'loan_amnt',
#'funded_amnt',
#'funded_amnt_inv',
#'installment',
#'annual_inc',
'dti',
'delinq_2yrs',
'inq_last_6mths',
'mths_since_last_delinq',
'mths_since_last_record',
'open_acc',
'pub_rec',
#'revol_bal',
#'total_acc',
#'out_prncp',
#'out_prncp_inv',
#'total_pymnt',
#'total_pymnt_inv',
#'total_rec_prncp',
#'total_rec_int',
#'total_rec_late_fee',
'recoveries',
'collection_recovery_fee',
#'last_pymnt_amnt',
'collections_12_mths_ex_med',
'mths_since_last_major_derog',
'policy_code',
'annual_inc_joint',
'dti_joint',
'acc_now_delinq',
'tot_coll_amt',
'tot_cur_bal',
'open_acc_6m',
'open_il_6m',
'open_il_12m',
'open_il_24m',
'mths_since_rcnt_il',
#'total_bal_il',
'il_util',
'open_rv_12m',
'open_rv_24m',
'max_bal_bc',
'all_util',
#'total_rev_hi_lim',
'inq_fi',
#'total_cu_tl',
'inq_last_12m',
'acc_open_past_24mths',
'avg_cur_bal',
'bc_open_to_buy',
'bc_util',
'chargeoff_within_12_mths',
'delinq_amnt',
'mo_sin_old_il_acct',
'mo_sin_old_rev_tl_op',
'mo_sin_rcnt_rev_tl_op',
'mo_sin_rcnt_tl',
'mort_acc',
'mths_since_recent_bc',
'mths_since_recent_bc_dlq',
'mths_since_recent_inq',
'mths_since_recent_revol_delinq',
'num_accts_ever_120_pd',
'num_actv_bc_tl',
'num_actv_rev_tl',
'num_bc_sats',
'num_bc_tl',
'num_il_tl',
'num_op_rev_tl',
'num_rev_accts',
'num_rev_tl_bal_gt_0',
'num_sats',
'num_tl_120dpd_2m',
'num_tl_30dpd',
'num_tl_90g_dpd_24m',
'num_tl_op_past_12m',
'pct_tl_nvr_dlq',
'percent_bc_gt_75',
'pub_rec_bankruptcies',
'tax_liens',
#'tot_hi_cred_lim',
#'total_bal_ex_mort',
#'total_bc_limit',
#'total_il_high_credit_limit'
               ], 1, inplace=True)

In [101]:
y2015.head()

id  loan_amnt  funded_amnt  funded_amnt_inv  installment  \
0  68009401.0    16000.0      16000.0          16000.0       379.39   
1  68354783.0     9600.0       9600.0           9600.0       298.58   
2  68466916.0    25000.0      25000.0          25000.0       777.55   
3  68466961.0    28000.0      28000.0          28000.0       858.05   
4  68495092.0     8650.0       8650.0           8650.0       320.99   

   annual_inc loan_status  revol_bal  total_acc  out_prncp  ...  \
0     48000.0     Current    19108.0       19.0   13668.88  ...   
1     60000.0     Current     7722.0        9.0    6635.69  ...   
2    109000.0  Fully Paid    20862.0       19.0       0.00  ...   
3     92000.0     Current    51507.0       24.0   19263.77  ...   
4     55000.0  Fully Paid     9568.0       19.0       0.00  ...   

   total_rec_int  total_rec_late_fee  last_pymnt_amnt  total_bal_il  \
0        2188.56                 0.0           379.39       12221.0   
1         608.66                 0.0           298.58       47665.0   
2        1224.23                 0.0         20807.39       47194.0   
3        1535.13                 0.0           858.05       23413.0   
4         540.49                 0.0          8251.42        9358.0   

   total_rev_hi_lim  total_cu_tl  tot_hi_cred_lim  total_bal_ex_mort  \
0          284700.0          0.0         298100.0            31329.0   
1           13000.0          0.0          88635.0            55387.0   
2           38400.0          0.0         373572.0            68056.0   
3           79900.0          1.0         304003.0            74920.0   
4           20750.0          0.0          38998.0            18926.0   

   total_bc_limit  total_il_high_credit_limit  
0        281300.0                     13400.0  
1         12500.0                     75635.0  
2         38400.0                     82117.0  
3         41500.0                     42503.0  
4          2750.0                     18248.0  

[5 rows x 24 columns]

In [102]:
y2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421095 entries, 0 to 421094
Data columns (total 24 columns):
id                            421095 non-null float64
loan_amnt                     421095 non-null float64
funded_amnt                   421095 non-null float64
funded_amnt_inv               421095 non-null float64
installment                   421095 non-null float64
annual_inc                    421095 non-null float64
loan_status                   421095 non-null object
revol_bal                     421095 non-null float64
total_acc                     421095 non-null float64
out_prncp                     421095 non-null float64
out_prncp_inv                 421095 non-null float64
total_pymnt                   421095 non-null float64
total_pymnt_inv               421095 non-null float64
total_rec_prncp               421095 non-null float64
total_rec_int                 421095 non-null float64
total_rec_late_fee            421095 non-null float64
last_pymnt_amnt           

In [103]:
X = y2015.drop('loan_status', 1)
X = X.dropna(axis=1)
Y = y2015['loan_status']

# PCA

In [104]:
from matplotlib.mlab import PCA as mlabPCA
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA 

sklearn_pca = PCA(n_components=3)
X_sklearn = sklearn_pca.fit_transform(X)

print(
    'The percentage of total variance in the dataset explained by each',
    'component from Sklearn PCA.\n',
    sklearn_pca.explained_variance_ratio_
)



The percentage of total variance in the dataset explained by each component from Sklearn PCA.
 [9.99514353e-01 3.73481458e-04 5.08010675e-05]


# Runing Random Forest Model

In [105]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

# import warnings filter
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)


In [106]:
rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, X, Y, cv=10)

array([0.88945881, 0.97254874, 0.96896298, 0.96561468, 0.96613631,
       0.96689622, 0.96544682, 0.96295329, 0.96214406, 0.96102693])

In [107]:
Z = pd.get_dummies(X)
cross_val_score(rfc, Z, Y, cv=10)

array([0.87668305, 0.97252499, 0.96893923, 0.96599463, 0.96563762,
       0.96739492, 0.96511435, 0.9639032 , 0.96288028, 0.96036194])

In [108]:
cross_val_score(rfc, X_sklearn, Y, cv=10)

array([0.68245827, 0.22291088, 0.18066538, 0.17458621, 0.11588696,
       0.09128473, 0.07062623, 0.0743784 , 0.13358824, 0.24628319])