In [62]:
#Initializing
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import statistics

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix

#import warnings filter - ignore all future warnings
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)

#Loading Working Data - https://www.kaggle.com/ronitf/heart-disease-uci
df = pd.read_csv('/Users/Kevin/Files/Thinkful/Data Files/heart.csv')

#Loading Raw Unformatted Data from Source- http://archive.ics.uci.edu/ml/datasets/Heart+Disease
raw_df = pd.read_csv("/Users/Kevin/Files/Thinkful/Data Files/processed.cleveland.data")

In [63]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [64]:
X = df.drop(['target'], 1)
Y = df.target

In [65]:
#Split dataset into training set and test set

#80% training and 20% test - Also setting random state to make results reproducable
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1221) 

# Test 1

In [68]:
# Establish and fit the model - hidden layer sizes
mlp = MLPClassifier(hidden_layer_sizes=(500,), random_state=1)
mlp.fit(X_train, Y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(500,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [69]:
md_score = mlp.score(X, Y)
md_cv_score = cross_val_score(mlp, X, Y, cv=10)
Y_pred = mlp.predict(X_test)
confusion_matrix_md = confusion_matrix(Y_test, Y_pred, labels=[1,0])

print('Accuracy Score: {:.2f}'.format(md_score))
print('\n')
print('Cross Validation Score:')
print(md_cv_score)
print('\n')
print('Confusion Matrix:')
print(confusion_matrix_md)

Accuracy Score: 0.83


Cross Validation Score:
[0.87096774 0.58064516 0.80645161 0.83870968 0.90322581 0.76666667
 0.8        0.86666667 0.62068966 0.79310345]


Confusion Matrix:
[[23  7]
 [ 4 27]]


# Test 2

In [70]:
# Establish and fit the model - activation
mlp = MLPClassifier(activation='identity', random_state=1)
mlp.fit(X_train, Y_train)

MLPClassifier(activation='identity', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [71]:
md_score = mlp.score(X, Y)
md_cv_score = cross_val_score(mlp, X, Y, cv=10)
Y_pred = mlp.predict(X_test)
confusion_matrix_md = confusion_matrix(Y_test, Y_pred, labels=[1,0])

print('Accuracy Score: {:.2f}'.format(md_score))
print('\n')
print('Cross Validation Score:')
print(md_cv_score)
print('\n')
print('Confusion Matrix:')
print(confusion_matrix_md)

Accuracy Score: 0.84


Cross Validation Score:
[0.87096774 0.80645161 0.77419355 0.93548387 0.90322581 0.7
 0.8        0.86666667 0.68965517 0.72413793]


Confusion Matrix:
[[29  1]
 [ 6 25]]


# Test 3

In [72]:
# Establish and fit the model - alpha
mlp = MLPClassifier(alpha=2, random_state=1)
mlp.fit(X_train, Y_train)

MLPClassifier(activation='relu', alpha=2, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [73]:
md_score = mlp.score(X, Y)
md_cv_score = cross_val_score(mlp, X, Y, cv=10)
Y_pred = mlp.predict(X_test)
confusion_matrix_md = confusion_matrix(Y_test, Y_pred, labels=[1,0])

print('Accuracy Score: {:.2f}'.format(md_score))
print('\n')
print('Cross Validation Score:')
print(md_cv_score)
print('\n')
print('Confusion Matrix:')
print(confusion_matrix_md)

Accuracy Score: 0.83


Cross Validation Score:
[0.87096774 0.80645161 0.83870968 0.83870968 0.87096774 0.76666667
 0.86666667 0.9        0.68965517 0.68965517]


Confusion Matrix:
[[25  5]
 [ 4 27]]


# Test 4

In [78]:
# Establish and fit the model - learning rate
mlp = MLPClassifier(learning_rate='adaptive', random_state=1)
mlp.fit(X_train, Y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='adaptive',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [79]:
md_score = mlp.score(X, Y)
md_cv_score = cross_val_score(mlp, X, Y, cv=10)
Y_pred = mlp.predict(X_test)
confusion_matrix_md = confusion_matrix(Y_test, Y_pred, labels=[1,0])

print('Accuracy Score: {:.2f}'.format(md_score))
print('\n')
print('Cross Validation Score:')
print(md_cv_score)
print('\n')
print('Confusion Matrix:')
print(confusion_matrix_md)

Accuracy Score: 0.83


Cross Validation Score:
[0.87096774 0.77419355 0.90322581 0.87096774 0.87096774 0.76666667
 0.83333333 0.9        0.68965517 0.68965517]


Confusion Matrix:
[[25  5]
 [ 4 27]]
